### ISSUE TITLE
Banana bugs

### ISSUE THREAD

**Issue by neverett** [openproduce/marzipan#64]
🍌 🐛 

## Perl files (/web/staff)

- [ ] accounts.pl -- `"Expression #2 of SELECT list is not in GROUP BY clause..."` - probably fixable by changing MySQL config to `SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));` as noted in #60 
- [ ] accounts.pl -- fetch() without execute() at line 81
- [ ] ar.pl -- Loads endlessly, no errors in Apache log
- [x] bank.pl is way deprecated
- [x] booze_prices.pl -- No errors, loads fine
- [ ] change_distributor.pl -- Unknown database 'marzipan' at line 6
- [x] customers.pl -- No errors, loads fine
- dash.pl
    - [ ] dash.pl --`"Expression #2 of SELECT list is not in GROUP BY clause..."` - probably fixable by changing MySQL config to `SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));` as noted in #60 
    - [ ] dash.pl -- Use of 'goto' to jump into a construct is deprecated at line 157
    - [ ] dash.pl -- DBD::mysql::st fetchrow_array failed: fetch() without execute() at line 152
    - [ ] dash.pl -- Illegal division by zero at line 178
- [ ] dash_all.pl -- Access denied for user 'op_bank'@'localhost'
- [ ] dash_booze.pl -- Access denied for user 'marzipan'@'localhost'
- delivery.pl
    - [ ] delivery.pl -- Unknown database 'marzipan' at line 6
    - [ ] delivery.pl -- Can't call method "prepare" on an undefined value at line 17
- [ ] hours.pl -- Unknown database 'marzipan' at line 26
- [ ] pretax.pl -- Weird escaping bug, see #61 

## Python files (/web/staff/optools)

Organized these by error:

- [ ] accounts.py -- "`Expression #2 of SELECT list is not in GROUP BY clause..."` - probably fixable by changing MySQL config to `SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));` as noted in #60
- [ ] make_dinnerrush_sales_csv.py -- "`Expression #2 of SELECT list is not in GROUP BY clause..."` - probably fixable by changing MySQL config to `SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));` as noted in #60
- [ ] item_graphs.py -- No module named 'matplotlib'
- [ ] item_info.py -- No module named 'matplotlib'
- [ ] sales_graph.py -- No module named 'matplotlib'
- [ ] add_items_js.py -- JS Error: incorrect arguments. given ['name', 'price_unit', 'taxcat', 'size_unit', 'count', 'price_id', 'action', 'categories', 'itemsize', 'case_unit'] (seems like I input things correctly?)
